#!/bin/bash
set -e

# Write the project-zshrc loader with the resolved workspace path. .zshrc sources
# it after the feature drop-ins, so committed project config (*.zsh) wins over
# features and the gitignored personal .overrides.zsh wins last. Sourced live
# from the bind-mounted workspace — edits show up in any new terminal, no rebuild.
WS="${1:-$PWD}"
ZDIR="$WS/.devcontainer/zshrc.d"
cat > "$HOME/.devcontainer-project-zshrc.zsh" << EOF
# Auto-generated by core create.sh — do not edit. Sources project (committed)
# then personal (gitignored .overrides.zsh) interactive-zsh from the workspace.
_dcz="$ZDIR"
if [ -d "\$_dcz" ]; then
  for _f in "\$_dcz"/*.zsh(N); do [ -r "\$_f" ] && source "\$_f"; done
  [ -r "\$_dcz/.overrides.zsh" ] && source "\$_dcz/.overrides.zsh"
fi
unset _f _dcz
EOF

# Merge the oh-my-zsh plugin registry into the .zshrc plugins=() array.
# Runs after every feature's install.sh, so all <feature>.conf files are
# present. git/fzf are core's always-on baseline. Regenerated from the
# registry each create, so it's idempotent across rebuilds.
PLUGDIR=/usr/local/share/devcontainer/zsh-plugins.d
if [ -f ~/.zshrc ] && grep -q '^plugins=(' ~/.zshrc; then
  plugins=$( { printf 'git\nfzf\n'; [ -d "$PLUGDIR" ] && cat "$PLUGDIR"/*.conf 2>/dev/null; } \
    | awk 'NF && !seen[$0]++' | tr '\n' ' ' | sed 's/ *$//' )
  sed -i "s/^plugins=(.*)/plugins=($plugins)/" ~/.zshrc
fi
